Домашнее задание

Взять датасет homework.csv
Описание датасета доступно тут - [https://www.kaggle.com/c/boston-housing/overview]

Решить задачу регрессии (как минимум один из):
[https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html]
[https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVR.html]
[https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeRegressor.html]

Оценить качество регрессии при помощи метрик:
[https://scikit-learn.org/stable/modules/generated/sklearn.metrics.mean_squared_error.html]
[https://scikit-learn.org/stable/modules/generated/sklearn.metrics.r2_score.html]
[https://scikit-learn.org/stable/modules/generated/sklearn.metrics.mean_absolute_error.html]

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('homework.csv')
df.head()

,ID,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,1,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,2,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,4,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
3,5,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
4,7,0.08829,12.5,7.87,0,0.524,6.012,66.6,5.5605,5,311,15.2,395.60,12.43,22.9

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 333 entries, 0 to 332
Data columns (total 15 columns):
ID         333 non-null int64
crim       333 non-null float64
zn         333 non-null float64
indus      333 non-null float64
chas       333 non-null int64
nox        333 non-null float64
rm         333 non-null float64
age        333 non-null float64
dis        333 non-null float64
rad        333 non-null int64
tax        333 non-null int64
ptratio    333 non-null float64
black      333 non-null float64
lstat      333 non-null float64
medv       333 non-null float64
dtypes: float64(11), int64(4)
memory usage: 39.1 KB

In [4]:
df.describe()

,ID,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
count,333.000000,333.000000,333.000000,333.000000,333.000000,333.000000,333.000000,333.000000,333.000000,333.000000,333.000000,333.000000,333.000000,333.000000,333.000000
mean,250.951952,3.360341,10.689189,11.293483,0.060060,0.557144,6.265619,68.226426,3.709934,9.633634,409.279279,18.448048,359.466096,12.515435,22.768769
std,147.859438,7.352272,22.674762,6.998123,0.237956,0.114955,0.703952,28.133344,1.981123,8.742174,170.841988,2.151821,86.584567,7.067781,9.173468
min,1.000000,0.006320,0.000000,0.740000,0.000000,0.385000,3.561000,6.000000,1.129600,1.000000,188.000000,12.600000,3.500000,1.730000,5.000000
25%,123.000000,0.078960,0.000000,5.130000,0.000000,0.453000,5.884000,45.400000,2.122400,4.000000,279.000000,17.400000,376.730000,7.180000,17.400000
50%,244.000000,0.261690,0.000000,9.900000,0.000000,0.538000,6.202000,76.700000,3.092300,5.000000,330.000000,19.000000,392.050000,10.970000,21.600000
75%,377.000000,3.678220,12.500000,18.100000,0.000000,0.631000,6.595000,93.800000,5.116700,24.000000,666.000000,20.200000,396.240000,16.420000,25.000000
max,506.000000,73.534100,100.000000,27.740000,1.000000,0.871000,8.725000,100.000000,10.710300,24.000000,711.000000,21.200000,396.900000,37.970000,50.000000

In [6]:
# Видимо пустых значений нет и все значения числовые

In [5]:
df.columns

Index(['ID', 'crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad',
       'tax', 'ptratio', 'black', 'lstat', 'medv'],
      dtype='object')

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import  SVC

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score 

from sklearn.model_selection import train_test_split

In [7]:
# Формируем признаки и целевую переменную: будем прогонозировать стоимость жилья в Бостоне ('medv')
#по значениям признаков (все другие показатели)
X, y = df[['ID', 'crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad',
       'tax', 'ptratio', 'black', 'lstat',]], df['medv']

In [8]:
# Разделим данные на группу обучения и проверки (70/30)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [9]:
# Приводем данные к одному масштабу
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
X_train = pd.DataFrame(X_train, columns=X.columns)
X_test = pd.DataFrame(X_test, columns=X.columns)
X_train.head()

,ID,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat
0,0.405341,-0.405305,-0.471155,-0.190326,-0.243086,-0.106712,-0.521645,0.536939,0.149636,-0.662557,-0.632799,-0.045006,0.365869,0.838104
1,0.324273,-0.438740,1.042408,-1.309011,-0.243086,-0.756275,1.394157,-0.982153,0.161505,-0.322522,-1.108905,-0.045006,0.400729,-0.777136
2,-0.945797,-0.429028,-0.471155,-0.174386,-0.243086,-0.079647,-0.141963,0.150852,-0.493766,-0.435867,0.110392,-0.320961,0.396284,-0.053112
3,1.580832,-0.419386,-0.471155,2.394821,-0.243086,0.479700,-1.711413,1.070967,-0.954064,-0.662557,1.730316,0.736868,-0.479552,2.446259
4,-0.770149,-0.023739,-0.471155,1.212377,4.113767,2.843388,-1.262170,1.143133,-1.208179,-0.549212,-0.057987,-1.746732,0.438397,2.041033

## Линейная регрессия

In [15]:
# Построим линейную регресиию, где признаками будут ['ID', 'crim', 'zn', 'indus', 'chas', 'nox', 'rm',
#'age', 'dis', 'rad', 'tax', 'ptratio', 'black', 'lstat',], которые будут определять стоимость
# жилья в Бостоне ('medv')

In [21]:
from sklearn.metrics import mean_absolute_error
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

reg = LinearRegression().fit(X_train, y_train)
print('Weights: {}'.format(reg.coef_))
print('Bias: {}'.format(reg.intercept_))

pred_values = reg.predict(df[['ID', 'crim', 'zn', 'indus', 'chas', 'nox', 'rm',\
                                'age', 'dis', 'rad', 'tax', 'ptratio', 'black', 'lstat',]])
print('Error: {}'.format(mean_absolute_error(pred_values, y)))

y_pred = reg.predict(X_test)

print("R2: \t", r2_score(y_test, y_pred))

print('Точность предсказания модели: ', reg.score(X_test, y_test))

Weights: [-0.46984358 -0.20958273  0.65080948 -0.0598484   0.51581048 -1.71968747
  2.37181924  0.4499794  -2.36587875  3.0799632  -1.76996625 -1.94598611
  1.05456288 -4.56913874]
Bias: 22.67639484978541
Error: 485.31926415887307
R2: 	 0.7275360011593983
Точность предсказания модели:  0.7275360011593983

In [ ]:
# Точность предсказания модели 73% - не очень высока, скорее всего,
#слишком много признаков, на основании которых строиться прогноз стоимости ('medv')

## SVR - Epsilon-Support Vector Regression

In [19]:
from sklearn import svm

clf = svm.SVR(kernel='linear')
clf.fit(X_train, y_train)
confidence = clf.score(X_test, y_test)
y_pred = reg.predict(X_test)
print('Точность предсказания модели: ', confidence)
print("R2: \t", r2_score(y_test, y_pred))

Точность предсказания модели:  0.6962130108350292
R2: 	 0.7275360011593983

In [20]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_train, y_pred)
mean_absolute_error(y_true, y_pred, multioutput='raw_values')

ValueError: Found input variables with inconsistent numbers of samples: [233, 100]

In [ ]:
# не подскажите, как сделать правильно?

## Decision Tree Regression

In [15]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeRegressor

In [24]:
regr_1 = DecisionTreeRegressor(max_depth=4)
regr_1.fit(X_train, y_train)

DecisionTreeRegressor(criterion='mse', max_depth=4, max_features=None,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=None, splitter='best')

In [25]:
y_pred = regr_1.predict(X_test)
print('Точность предсказания модели: ', confidence)
print("R2: \t", r2_score(y_test, y_pred))

Точность предсказания модели:  0.6962130108350292
R2: 	 0.8718444738912832